### ISSUE TITLE
crashing on ios

### ISSUE THREAD

**Issue by nativeB** [alexziskind1/nativescript-oauth2#160]
### Which platform(s) does your issue occur on?
- iOS
- emulator 

### Please, provide the following version numbers that your issue occurs with:

- CLI: 7.0.12

### Please, tell us how to recreate the issue in as much detail as possible. 
ns clean 
npm i 
build to device

***** Fatal JavaScript exception - application has been terminated. *****
NativeScript encountered a fatal error: Uncaught ReferenceError: NativeClass is not defined
at
setup(file: node_modules/nativescript-oauth2/delegate/index.ios.js:30:8)
at ../node_modules/nativescript-oauth2/delegate/index.js(file: node_modules/nativescript-oauth2/delegate/index.ios.js:35:41)
at __webpack_require__(file: src/webpack/bootstrap:74:0)
at ../node_modules/nativescript-oauth2/oauth.js(file: node_modules/nativescript-oauth2/oauth.js:1:0)
at __webpack_require__(file: src/webpack/bootstrap:74:0)
at ./auth/auth-service.js(file: src/auth/auth-service.js:1:0)
at __webpack_require__(file: src/webpack/bootstrap:74:0)
at ../node_modules/babel-loader/lib/index.js!../node_modules/vue-loader/lib/index.js?!./native/public/SignInWith.vue?vue&type=script&lang=js&(file:///app/bundle.js:33318:76)
at __webpack_require__(file: src/webpack/bootstrap:74:0)
at ./native/public/SignInWith.vue?vue&type=script&lang=js&(file: src/native/public/SignInWith.vue?871f:1:0)
at __webpack_require__(file: src/webpack/bootstrap:74:0)
at ./native/public/SignInWith.vue(file: src/native/public/SignInWith.vue:1:0)
at __webpack_require__(file:///app/run<…>
(CoreFoundation) *** Terminating app due to uncaught exception 'NativeScript encountered a fatal error: Uncaught ReferenceError: NativeClass is not defined
at
setup(file: node_modules/nativescript-oauth2/delegate/index.ios.js:30:8)
at ../node_modules/nativescript-oauth2/delegate/index.js(file: node_modules/nativescript-oauth2/delegate/index.ios.js:35:41)
at __webpack_require__(file: src/webpack/bootstrap:74:0)
at ../node_modules/nativescript-oauth2/oauth.js(file: node_modules/nativescript-oauth2/oauth.js:1:0)
at __webpack_require__(file: src/webpack/bootstrap:74:0)
at ./auth/auth-service.js(file: src/auth/auth-service.js:1:0)
at __webpack_require__(file: src/webpack/bootstrap:74:0)
at ../node_modules/babel-loader/lib/index.js!../node_modules/vue-loader/lib/index.js?!./native/public/SignInWith.vue?vue&type=script&lang=js&(file:///app/bundle.js:33318:76)
at __webpack_require__(file: src/webpack/bootstrap:74:0)
at ./native/public/SignInWith.vue?vue&type=script&lang=js&(file: src/native/public/SignInWith.vue?871f:1:0)
at __webpack_require__(file: src/webpack/bootstrap:74:0)
at ./native/public/SignInWith.vue(file:///app/bundle.js:113<…>

**Comment by nithinjadhav** [comment]
Im facing the same issue.

**Comment by Benoye** [comment]
Facing the same issue !

**Comment by nativeB** [comment]
currently using 3.0.3 , what works for me is taking out the caret  so i don't get minor versions.so maybe 3.0.4 is the issue?

**Comment by Benoye** [comment]
Hi guys !
@nativeB is right, the working version is `3.0.3` !
I was using `3.0.4` and rolled back to `3.0.3` and now it is working well..

I removed the carret in `package.json` as @nativeB said, to make sure it does not update for now :)
