### ISSUE TITLE
Angular demo fails in {N} shared project

### ISSUE THREAD

**Issue by armache** [alexziskind1/nativescript-oauth2#76]
### Which platform(s) does your issue occur on?
- Android 
- 8.0.0
- Huawei P10

### Please, provide the following version numbers that your issue occurs with:

- CLI: 6.1.2
- Cross-platform modules: 6.0.7
- Runtime(s): 6.1.2
- Plugin(s):
"devDependencies": {
    "@angular-devkit/build-angular": "~0.800.0",
    "@angular/cli": "^8.3.14",
    "@angular/compiler-cli": "~8.0.1",
    "@nativescript/schematics": "~0.7.0",
    "@nativescript/tslint-rules": "~0.0.2",
    "@types/jasmine": "~3.3.8",
    "@types/jasminewd2": "~2.0.3",
    "@types/node": "~8.9.4",
    "codelyzer": "^5.0.0",
    "jasmine-core": "~3.4.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~4.1.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~2.0.1",
    "karma-jasmine": "~2.0.1",
    "karma-jasmine-html-reporter": "^1.4.0",
    "nativescript-dev-webpack": "~1.0.0",
    "protractor": "~5.4.0",
    "ts-node": "~7.0.0",
    "tslint": "~5.15.0",
    "typescript": "~3.4.3"
  }

### Please, tell us how to recreate the issue in as much detail as possible. 
I created Angular Nativescript shared project by running the command below:
ng new --collection=@nativescript/schematics --name=my-app --shared

Then I copied required files from Angular demo project. I can successfully build the project locally. The problem occurs when I try to test the app on a device. I run "tns preview" then after scanning the QR code I am getting the following error:

LOG from device Ara: An uncaught Exception occurred on "main" thread.
Unable to resume activity {org.nativescript.preview/com.tns.playlivesync.NativeScriptActivity}: com.tns.NativeScriptException: Calling js method onActivityResumed failed
TypeError: Cannot read property 'resumeWithUrl' of undefined

StackTrace:
java.lang.RuntimeException: Unable to resume activity {org.nativescript.preview/com.tns.playlivesync.NativeScriptActivity}: com.tns.NativeScriptException: Calling js method onActivityResumed failed
TypeError: Cannot read property 'resumeWithUrl' of undefined
        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4282)
        at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4322)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3417)
        at android.app.ActivityThread.-wrap12(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1994)
        at android.os.Handler.dispatchMessage(Handler.java:108)
        at android.os.Looper.loop(Looper.java:166)
        at android.app.ActivityThread.main(ActivityThread.java:7523)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)
Caused by: com.tns.NativeScriptException: Calling js method onActivityResumed failed
TypeError: Cannot read property 'resumeWithUrl' of undefined
        at com.tns.Runtime.callJSMethodNative(Native Method)
        at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1209)
        at com.tns.Runtime.callJSMethodImpl(Runtime.java:1096)
        at com.tns.Runtime.callJSMethod(Runtime.java:1083)
        at com.tns.Runtime.callJSMethod(Runtime.java:1063)
        at com.tns.Runtime.callJSMethod(Runtime.java:1055)
        at com.tns.gen.android.app.Application_ActivityLifecycleCallbacks.onActivityResumed(Application_ActivityLifecycleCallbacks.java:32)
        at android.app.Application.dispatchActivityResumed(Application.java:227)
        at android.app.Activity.onResume(Activity.java:1415)
        at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1364)
        at android.app.Activity.performResume(Activity.java:7490)
        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4250)
        ... 10 more

Could you please advice if I am missing something?

### Is there any code involved? 
 Source code is available at https://github.com/armache/angular-ns-login

**Comment by alexziskind1** [comment]
This plugin won't work with the nativescript preview app because the app needs to register custom url scheme with the operating system. You need to test this on a proper environment with native tools installed.

**Comment by fouladi1983** [comment]
here i have same issue
i tired the google tutorial from [](https://www.youtube.com/watch?v=Ix0bXZeyhK0) and as @alexziskind1 explained i created a project in console developers of google and it worked perfectly in a nativescript test project but when i use same code in nativescript angular(angular 8) project it send user to login page of google and user can login but when user redirected to main app, user attempts TypeError: Cannot read property 'resumeWithUrl' of undefined
considering the url scheme and redirect url are exactly the urls i used in nativescript test app

**Comment by jpnobrega** [comment]
I don't have ios operacional systems =(
