### ISSUE TITLE
cannot build angular demo due to errors

### ISSUE THREAD

**Issue by aquinn637** [alexziskind1/nativescript-oauth2#84]
I downloaded the repo here for the demo projects onto my machine. I navigated to the angular demo folder and ran this command: **tns debug android**

I cannot run the build and there are a number of errors:

```
ERROR in ../src/delegate/delegate.android.ts(10,26): error TS2339: Property 'content' does not exist on type 'typeof android'.
../src/delegate/delegate.ios.ts(3,12): error TS2304: Cannot find name 'UIApplicationDelegate'.
../src/delegate/delegate.ios.ts(4,48): error TS2304: Cannot find name 'UIResponder'.
../src/delegate/delegate.ios.ts(5,14): error TS2304: Cannot find name 'UIApplicationDelegate'.
../src/delegate/delegate.ios.ts(16,18): error TS2304: Cannot find name 'UIApplication'.
../src/delegate/delegate.ios.ts(17,10): error TS2304: Cannot find name 'NSURL'.
../src/delegate/delegate.ios.ts(18,14): error TS2304: Cannot find name 'NSDictionary'.
../src/delegate/delegate.ios.ts(25,18): error TS2304: Cannot find name 'UIApplication'.
../src/delegate/delegate.ios.ts(26,10): error TS2304: Cannot find name 'NSURL'.
../src/delegate/delegate.ios.ts(33,34): error TS2304: Cannot find name 'NSURL'.
../src/delegate/delegate.ts(10,26): error TS2339: Property 'content' does not exist on type 'typeof android'.
../src/oauth.ts(110,9): error TS2304: Cannot find name 'NSHTTPCookieStorage'.
../src/oauth.ts(113,23): error TS2304: Cannot find name 'NSHTTPCookie'.
../src/oauth.ts(113,39): error TS2304: Cannot find name 'NSHTTPCookie'.
../src/oauth.ts(116,13): error TS2304: Cannot find name 'NSHTTPCookieStorage'.
../src/oauth.ts(121,25): error TS2304: Cannot find name 'WKWebsiteDataStore'.
../src/oauth.ts(123,9): error TS2304: Cannot find name 'WKWebsiteDataStore'.
../src/oauth.ts(125,30): error TS2304: Cannot find name 'WKWebsiteDataRecord'.
../src/oauth.ts(152,35): error TS2339: Property 'webkit' does not exist on type 'typeof android'.
../src/pkce-util.android.ts(2,45): error TS2339: Property 'util' does not exist on type 'typeof android'.
../src/pkce-util.android.ts(2,75): error TS2339: Property 'util' does not exist on type 'typeof android'.
../src/pkce-util.android.ts(2,108): error TS2339: Property 'util' does not exist on type 'typeof android'.
../src/pkce-util.android.ts(5,29): error TS2339: Property 'create' does not exist on type 'ArrayConstructor'.
../src/pkce-util.android.ts(6,7): error TS2304: Cannot find name 'java'.
../src/pkce-util.android.ts(7,18): error TS2339: Property 'util' does not exist on type 'typeof android'.
../src/pkce-util.android.ts(11,26): error TS2304: Cannot find name 'java'.
../src/pkce-util.android.ts(12,29): error TS2304: Cannot find name 'java'.
../src/pkce-util.android.ts(14,18): error TS2339: Property 'util' does not exist on type 'typeof android'.
../src/pkce-util.ios.ts(4,22): error TS2304: Cannot find name 'NSMutableData'.
../src/pkce-util.ios.ts(5,26): error TS2304: Cannot find name 'SecRandomCopyBytes'.
../src/pkce-util.ios.ts(5,45): error TS2304: Cannot find name 'kSecRandomDefault'.
../src/pkce-util.ios.ts(14,23): error TS2304: Cannot find name 'NSData'.
../src/pkce-util.ios.ts(14,32): error TS2304: Cannot find name 'NSString'.
../src/pkce-util.ios.ts(14,89): error TS2304: Cannot find name 'NSUTF8StringEncoding'.
../src/pkce-util.ios.ts(15,25): error TS2304: Cannot find name 'NSMutableData'.
../src/pkce-util.ios.ts(15,41): error TS2304: Cannot find name 'NSMutableData'.
../src/pkce-util.ios.ts(16,3): error TS2304: Cannot find name 'CC_SHA256'.
../src/pkce-util.ios.ts(20,41): error TS2304: Cannot find name 'NSData'.
../src/pkce-util.ts(2,45): error TS2339: Property 'util' does not exist on type 'typeof android'.
../src/pkce-util.ts(2,75): error TS2339: Property 'util' does not exist on type 'typeof android'.
../src/pkce-util.ts(2,108): error TS2339: Property 'util' does not exist on type 'typeof android'.
../src/pkce-util.ts(5,29): error TS2339: Property 'create' does not exist on type 'ArrayConstructor'.
../src/pkce-util.ts(6,7): error TS2304: Cannot find name 'java'.
../src/pkce-util.ts(7,18): error TS2339: Property 'util' does not exist on type 'typeof android'.
../src/pkce-util.ts(11,26): error TS2304: Cannot find name 'java'.
../src/pkce-util.ts(12,29): error TS2304: Cannot find name 'java'.
../src/pkce-util.ts(14,18): error TS2339: Property 'util' does not exist on type 'typeof android'.
../src/tns-oauth-native-view-controller.ios.ts(13,56): error TS2304: Cannot find name 'NSObject'.
../src/tns-oauth-native-view-controller.ios.ts(14,14): error TS2304: Cannot find name 'SFSafariViewControllerDelegate'.
../src/tns-oauth-native-view-controller.ios.ts(15,34): error TS2304: Cannot find name 'SFSafariViewControllerDelegate'.
../src/tns-oauth-native-view-controller.ios.ts(18,33): error TS2304: Cannot find name 'SFSafariViewController'.
         + setting applicationId
         + applying user-defined configuration from C:\Users\aubrey\Source\Repos\nativescript-oauth2-master (1)\nativescript-oauth2-master\demo-angular\App_Resources\Android\app.gradle
         + using andorid X library androidx.legacy:legacy-support-v4:1.0.0'. Did you mean 'Array'?
         + adding nativescript runtime package dependency: nativescript-optimized-with-inspector
         + adding aar plugin dependency: C:\Users\aubrey\Source\Repos\nativescript-oauth2-master (1)\nativescript-oauth2-master\demo-angular\node_modules\tns-core-modules-widgets\platforms\android\widgets-release.aar
Exception in thread "main" java.io.IOException: Couldn't find 'C:\Users\aubrey\Source\Repos\nativescript-oauth2-master (1)\nativescript-oauth2-master\demo-angular\platforms\android\build-tools\sbg-bindings.txt' bindings input file. Most probably there's an error in the JS Parser execution. You can run JS Parser with verbose logging by executing "node 'C:\Users\aubrey\Source\Repos\nativescript-oauth2-master (1)\nativescript-oauth2-master\demo-angular\platforms\android\build-tools\jsparser\js_parser.js' enableErrorLogging".
        at org.nativescript.staticbindinggenerator.Generator.generateBindings(Generator.java:126)
        at org.nativescript.staticbindinggenerator.Generator.writeBindings(Generator.java:97)
        at org.nativescript.staticbindinggenerator.Main.main(Main.java:50)

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:runSbg'.
> Process 'command 'C:\Program Files\AdoptOpenJDK\jdk8u192-b12\bin\java.exe'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 22s
Unable to apply changes on device: 4d2bc6bf. Error is: Command gradlew.bat failed with exit code 1.
PS C:\Users\aubrey\Source\Repos\nativescript-oauth2-master (1)\nativescript-oauth2-master\demo-angular>
```

**Comment by AmrMMorad** [comment]
Do you manage to solve the problem?
